version: "2"
services:
    svn2git:
        image: redmatter/svn2git-workspace
        volumes:
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
            - ./workspace:/workspace
        environment:
            - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
        network_mode: "host"